linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - dupl
    - exportloopref
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
  fast: false
  disable-all: true
