name: build

on:
  push:
    branches:
    tags:
    paths-ignore:
      - ".github/workflows/ci-v2.yml"
      - ".github/workflows/ci-v3.yml"
      - "v2/**"
      - "v3/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/ci-v2.yml"
      - ".github/workflows/ci-v3.yml"
      - "v2/**"
      - "v3/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
        id: go

      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        run: |
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov
          go build -race

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.60.1"

      - name: install goveralls, submit coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
